### ISSUE TITLE
Add owners

### ISSUE THREAD

**Issue by dominicbarnes** [duojs/myth#10]
@MatthewMueller can you add myself (`dominicbarnes`) and @stephenmathieson (basically @duojs/owners) as owners for `duo-myth` on npm?

**Comment by MatthewMueller** [comment]
yep done

**Comment by dominicbarnes** [comment]
Thanks :)

**Comment by stephenmathieson** [comment]
i think there's a script in `component/` that adds all owners to npm...

**Comment by stephenmathieson** [comment]
https://github.com/repo-utils/npm-org-rights

**Comment by MatthewMueller** [comment]
haha good call
